AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.6
  Exclude:
  - 'bin/**/*'
  - 'gemfiles/**/*'
  - 'tmp/**/*'

Style/Documentation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false
