language: ruby
rvm: 2.5.1
branches:
  only: master
cache: bundler
before_install:
- gem update --system
- gem install bundler
script: bin/rubocop && bin/rake
gemfile:
- gemfiles/5.1.gemfile
- gemfiles/5.2.gemfile
