name: Main
on:
- push
- pull_request_target
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gemfile:
        - "6.0"
        - "6.1"
        - "7.0"
    env:
      BUNDLE_GEMFILE: gemfiles/${{ matrix.gemfile }}.gemfile
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.1"
        bundler-cache: true
    - name: Lint and test
      run: |
        bundle exec rubocop --parallel
        bundle exec rake test

  valgrind:
    name: Valgrind
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: "3.1"
        bundler-cache: true
    - run: bundle exec test:valgrind

  automerge:
    name: AutoMerge
    needs: [ci, valgrind]
    runs-on: ubuntu-latest
    if: github.event_name == "pull_request_target" && (github.actor == github.repository_owner || github.actor == "dependabot[bot]")
    steps:
    - uses: actions/github-script@v3
      with:
        script: |
          github.pulls.merge({
            owner: context.payload.repository.owner.login,
            repo: context.payload.repository.name,
            pull_number: context.payload.pull_request.number
          })
